name: Python Serverless News Bot (Keyword Hunter)

# on:
#   schedule:
#     - cron: '*/15 * * * *'
#   workflow_dispatch:

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 코드 가져오기
        uses: actions/checkout@v3

      - name: 파이썬 3.10 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 라이브러리 설치
        run: |
          pip install -r requirements.txt

      - name: 봇 실행
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SEARCH_KEYWORD: ${{ secrets.SEARCH_KEYWORD }}
        run: |
          python main.py
